version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm run build
      - run: cd client && npm run build
      - run: cd server && npm run pack
      - save_cache:
          paths:
            - client\node_modules
            - server\node_modules
          key: v1-dependencies-{{ checksum "package.json" }}