version: 2.1

jobs:
  build_client:
    docker:
      - image: circleci/node
    working_directory: ~/$WORK_DIR
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "client/package.json" }}
            - v1-dependencies-
      - run: npm i
      - run: npm run build-client
      - save_cache:
          paths:
            - ./client/node_modules
          key: v1-dependencies-{{ checksum "client/package.json" }}
      - persist_to_workspace:
          root: ~/$WORK_DIR
          paths:
            - $CLIENT_PACKAGE
  build_server:
    docker:
      - image: circleci/node
    working_directory: ~/$WORK_DIR
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "server/package.json" }}
            - v1-dependencies-
      - run: npm i
      - run: npm run build-server
      - save_cache:
          paths:
            - ./server/node_modules
          key: v1-dependencies-{{ checksum "server/package.json" }}
      - persist_to_workspace:
          root: ~/$WORK_DIR
          paths:
            - $SERVER_PACKAGE
  deploy_client:
    docker:
      - image: alpine/git
    working_directory: ~/$WORK_DIR
    steps:
      - checkout
      - attach_workspace:
          at: ~/$WORK_DIR
      - run: git tag $SOFTWARE_VERSION.$CIRCLE_BUILD_NUM
      - run: git push origin master --tags
  deploy_server:
    docker:
      - image: circleci/python
    working_directory: ~/$WORK_DIR
    steps:
      - checkout
      - attach_workspace:
          at: ~/$WORK_DIR
      - run: sudo pip install awscli
      - run: aws s3 sync $SERVER_PACKAGE s3://$AWS_S3_BUCKET/$SERVER_PACKAGE --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_client
      - build_server
      - deploy_client:
          requires:
            - build_client
          filters:
            branches:
              only: master
      - deploy_server:
          requires:
            - build_server
          filters:
            branches:
              only: master
    