version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.8

jobs:
  build_client:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "client/package.json" }}
            - v1-dependencies-
      - run: npm i
      - run: npm run build-client
      - save_cache:
          paths:
            - ./client/node_modules
          key: v1-dependencies-{{ checksum "client/package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ${CLIENT_PACKAGE}
  build_server:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "server/package.json" }}
            - v1-dependencies-
      - run: npm i
      - run: npm run build-server
      - save_cache:
          paths:
            - ./server/node_modules
          key: v1-dependencies-{{ checksum "server/package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ${SERVER_PACKAGE}
  deploy_client:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: git tag ${SOFTWARE_VERSION}.$CIRCLE_BUILD_NUM
      - run: git push origin master --tags
  deploy_server:
    docker:
      - image: circleci/python
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - aws-s3/sync:
          from: ${SERVER_PACKAGE}
          to: s3://${AWS_S3_BUCKET}/habitat-${SOFTWARE_VERSION}.${CIRCLE_BUILD_NUM}.zip
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          aws-region: AWS_REGION
          overwrite: false

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_client
      - build_server
      - deploy_client:
          requires:
            - build_client
          filters:
            branches:
              only: master
      - deploy_server:
          context: prd
          requires:
            - build_server
          filters:
            branches:
              only: master