version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.8

commands:
  sync:
    parameters:
      software_version:
        default: "0.1.0"
        type: string
      work_dir:
        default: "repo"
        type: string
      client_package:
        default: "client/dist"
        type: string
      server_package:
        default: "server/habitat.zip"
        type: string
      s3_bucket_name:
        default: "habitat-deploys-prd-eastus"
        type: string

jobs:
  build_client:
    parameters:
      work_dir:
        default: "client"
        type: string
      client_package:
        default: "client/dist"
        type: string
    docker:
      - image: circleci/node
    working_directory: ~/<< parameters.work_dir >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "client/package.json" }}
            - v1-dependencies-
      - run: npm i
      - run: npm run build-client
      - save_cache:
          paths:
            - ./client/node_modules
          key: v1-dependencies-{{ checksum "client/package.json" }}
      - persist_to_workspace:
          root: ~/<< parameters.work_dir >>
          paths:
            - << parameters.client_package >>
  build_server:
    parameters:
      work_dir:
        default: "client"
        type: string
      server_package:
        default: "server/habitat.zip"
        type: string
    docker:
      - image: circleci/node
    working_directory: ~/<< parameters.work_dir >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "server/package.json" }}
            - v1-dependencies-
      - run: npm i
      - run: npm run build-server
      - save_cache:
          paths:
            - ./server/node_modules
          key: v1-dependencies-{{ checksum "server/package.json" }}
      - persist_to_workspace:
          root: ~/<< parameters.work_dir >>
          paths:
            - << parameters.server_package >>
  deploy_client:
    parameters:
      work_dir:
        default: "client"
        type: string
      software_version:
        default: "0.1.0"
        type: string
    docker:
      - image: alpine/git
    working_directory: ~/<< parameters.work_dir >>
    steps:
      - checkout
      - attach_workspace:
          at: ~/<< parameters.work_dir >>
      - run: git tag << parameters.software_version >>.$CIRCLE_BUILD_NUM
      - run: git push origin master --tags
  deploy_server:
    parameters:
      work_dir:
        default: "client"
        type: string
      software_version:
        default: "0.1.0"
        type: string
      aws_bucket_name:
        default: "habitat-deploys-prd-eastus"
        type: string
      
    docker:
      - image: circleci/python
    working_directory: ~/<< parameters.work_dir >>
    steps:
      - checkout
      - attach_workspace:
          at: ~/<< parameters.work_dir >>
      - aws-s3/sync:
          from: << parameters.server_package >>
          to: s3://${AWS_S3_BUCKET}/habitat-<< parameters.server_package >>.$CIRCLE_BUILD_NUM.zip
          aws-access-key-id: $AWS_ACCESS_KEY
          aws-secret-access-key: $AWS_SECRET_KEY
          aws-region: us-east-1
          overwrite: false

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_client
      - build_server
      - deploy_client:
          requires:
            - build_client
          filters:
            branches:
              only: master
      - deploy_server:
          context: prd
          requires:
            - build_server
          filters:
            branches:
              only: master
    